#!/usr/bin/perl

use warnings;
use strict;
use 5.12.0;

use Fcntl qw( LOCK_EX LOCK_NB );
use File::NFSLock;

my $slave_check_file = "/SVN/is_svn_slave";

# integrity checks

my $repl_lock = File::NFSLock->new( $0, LOCK_EX|LOCK_NB );

ensure_slave( $slave_check_file );
lock_process();
caller_has_sudo();

sleep 10;

# functions

sub ensure_slave {

    my $slave_check_file = shift;

    die "$0 can only be run on a Slave SVN server!\n"
        if ! -e $slave_check_file;
}
sub lock_process {


    if ( ! $repl_lock ){
        die "$0 is already running... aborting this run\n";
    }
}
sub caller_has_sudo {

    my $running_as_user = getpwuid( $< );

    die "$0 needs to be called with sudo...aborting\n"
        if $running_as_user ne 'root';
}
